name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: 'gradle'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle build
        run: ./gradlew clean build --no-daemon

      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-reports-csv
          path: build/reports/jacoco/test/csv/testReport.csv
